/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/patient/vault/conditions/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Batch synchronize baseline health conditions
         * @description Replaces existing patient-declared baseline conditions with the provided list while preserving any doctor-verified or clinician-entered clinical records.
         */
        put: operations["syncBaselineConditions"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/conditions/baseline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["syncBaselineConditions_1"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/vault/conditions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all patient health conditions
         * @description Retrieves all health conditions, allergies, and past history recorded for the authenticated patient.
         */
        get: operations["getConditions"];
        put?: never;
        /**
         * Add a baseline health condition or allergy
         * @description Records a foundational patient-declared medical condition in the vault.
         */
        post: operations["addCondition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/vault/access-grants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a consultation access grant PIN
         * @description Generates a random 6-digit access code valid for 15 minutes to unlock doctor append access. Revokes any older open tokens.
         */
        post: operations["generateAccessGrant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctor/vault/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unlock patient vault via 6-digit access PIN
         * @description Validates and consumes a single-use 6-digit consultation access PIN. Unlocks patient demographics, baseline health records, and past consultation history for clinical review.
         */
        post: operations["unlockVault"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctor/test-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a numerical lab test result or biomarker measurement
         * @description Appends a structured numerical diagnostic test result for the patient. Permitted for General Practitioners, Specialists, and Lab Technicians with an active 24-hour vault session.
         */
        post: operations["recordTestResult"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctor/prescriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue a standalone or encounter-linked prescription
         * @description Issues an active prescription for a patient. Optionally links to a clinical encounter visit. Supports standalone prescription issuance and renewals.
         */
        post: operations["issuePrescription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/doctor/encounters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log an append-only clinical consultation encounter
         * @description Appends an immutable clinical encounter to the patient's record. Optionally records companion diagnoses as DOCTOR_VERIFIED conditions. Encounters are strictly immutable and cannot be edited or deleted once saved.
         */
        post: operations["createEncounter"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/patient": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new patient account
         * @description Creates a new User with ROLE_PATIENT and initializes their PatientProfile vault.
         */
        post: operations["registerPatient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register/doctor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a new doctor account
         * @description Creates a new User with ROLE_DOCTOR and registers their DoctorProfile with verified license.
         */
        post: operations["registerDoctor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Authenticate user and issue JWT
         * @description Validates user credentials and issues a signed JWT token with identity claims.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/prescriptions/{prescriptionId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update prescription lifecycle status
         * @description Transitions prescription status. Patients can mark their prescriptions as FULFILLED (pharmacy dispensing); prescribing doctors can mark prescriptions as CANCELLED (dosage correction or adverse reaction). Requires profile ownership.
         */
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/api/v1/patient/vault/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update patient profile baseline attributes
         * @description Updates baseline attributes (gender, height, weight) for the authenticated patient.
         */
        patch: operations["updateProfile"];
        trace?: never;
    };
    "/api/v1/patient/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get authenticated patient profile
         * @description Retrieves demographic and baseline attributes for the authenticated patient.
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update patient baseline attributes and profile
         * @description Updates baseline attributes (gender, height, weight) for the authenticated patient.
         */
        patch: operations["updateProfile_1"];
        trace?: never;
    };
    "/api/v1/admin/doctors/{doctorId}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Switch doctor permission role for demo presentations
         * @description Dynamically updates a doctor's active permission role (e.g. to LAB_TECHNICIAN, PHARMACIST, or GENERAL_PRACTITIONER) so role permission boundaries can be presented during live demonstrations.
         */
        patch: operations["updateDoctorRole"];
        trace?: never;
    };
    "/api/v1/patient/vault/timeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get consolidated chronological patient vault timeline
         * @description Retrieves complete chronological view of demographics, baseline conditions, and appended clinical consultations.
         */
        get: operations["getTimeline"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/vault/test-results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get patient diagnostic lab test results
         * @description Retrieves time-series lab test results for the patient sorted chronologically ascending (recordedAt ASC) for trend charting. Optionally filtered by testName.
         */
        get: operations["getTestResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/vault/prescriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List patient prescriptions
         * @description Retrieves all prescriptions issued for the authenticated patient, optionally filtered by status (ACTIVE, FULFILLED, CANCELLED).
         */
        get: operations["getPrescriptions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get currently authenticated user identity
         * @description Retrieves profile and identity details of the authenticated bearer token owner.
         */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/patient/vault/conditions/{conditionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a patient-declared health condition
         * @description Removes a condition from the vault. Patients can only delete PATIENT_DECLARED records.
         */
        delete: operations["deleteCondition"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Individual baseline health condition or allergy entry for synchronization */
        BaselineConditionItem: {
            /** @example Penicillin Allergy */
            title: string;
            /**
             * @example ALLERGY
             * @enum {string}
             */
            type: "ALLERGY" | "CHRONIC_CONDITION" | "LIFESTYLE" | "PAST_HISTORY" | "MEDICATION" | "SURGERY" | "OTHER";
            /**
             * @description Optional clinical or personal notes regarding the condition
             * @example Diagnosed in childhood
             */
            notes?: string;
        };
        /** @description Batch payload to replace and synchronize patient-declared baseline conditions */
        SyncBaselineConditionsRequest: {
            /** @description List of baseline condition items to set for the patient */
            conditions?: components["schemas"]["BaselineConditionItem"][];
        };
        /** @description Health condition or allergy record details */
        HealthConditionResponse: {
            /**
             * Format: uuid
             * @description Condition unique identifier
             * @example c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a22
             */
            id?: string;
            /**
             * @description Condition title or diagnosis name
             * @example Penicillin Allergy
             */
            title?: string;
            /**
             * @description Category of condition
             * @example ALLERGY
             * @enum {string}
             */
            type?: "ALLERGY" | "CHRONIC_CONDITION" | "LIFESTYLE" | "PAST_HISTORY" | "MEDICATION" | "SURGERY" | "OTHER";
            /**
             * @description Source origin of the record
             * @example PATIENT_DECLARED
             * @enum {string}
             */
            sourceType?: "PATIENT_DECLARED" | "DOCTOR_VERIFIED" | "CLINICIAN_ENTERED";
            /**
             * Format: date
             * @description Date recorded or reported
             * @example 2023-01-15
             */
            dateRecorded?: string;
            /**
             * @description Optional notes or details regarding condition
             * @example Mild hives on exposure
             */
            notes?: string;
            /**
             * Format: date-time
             * @description Timestamp when saved in vault
             */
            createdAt?: string;
        };
        ErrorResponse: {
            /** Format: date-time */
            timestamp?: string;
            /** Format: int32 */
            status?: number;
            error?: string;
            message?: string;
            path?: string;
            fieldErrors?: {
                [key: string]: string;
            };
        };
        /** @description Payload to record a patient-declared foundational health condition or allergy */
        CreateHealthConditionRequest: {
            /** @example Penicillin Allergy */
            title: string;
            /**
             * @example ALLERGY
             * @enum {string}
             */
            type: "ALLERGY" | "CHRONIC_CONDITION" | "LIFESTYLE" | "PAST_HISTORY" | "MEDICATION" | "SURGERY" | "OTHER";
            /**
             * Format: date
             * @description Date when condition was recorded or diagnosed (defaults to current date if omitted)
             * @example 2023-01-15
             */
            dateRecorded?: string;
        };
        /** @description Temporary consultation access grant token details */
        AccessGrantResponse: {
            /**
             * Format: uuid
             * @description Access grant unique identifier
             */
            id?: string;
            /**
             * @description 6-digit access code presented to clinician
             * @example 482910
             */
            accessCode?: string;
            /**
             * Format: date-time
             * @description Expiration timestamp (15 minutes from generation)
             */
            expiresAt?: string;
            /**
             * Format: int64
             * @description Remaining seconds until token expires
             * @example 900
             */
            remainingSeconds?: number;
            used?: boolean;
            /**
             * @description Whether the token has already been consumed by a clinician
             * @example false
             */
            isUsed?: boolean;
        };
        /** @description Request payload to unlock a patient's vault using their 6-digit consultation access PIN */
        UnlockVaultRequest: {
            /**
             * @description The 6-digit temporary PIN generated by the patient
             * @example 482910
             */
            accessCode: string;
        };
        /** @description Chronological clinical consultation record summary */
        ClinicalEncounterSummaryDto: {
            /**
             * Format: uuid
             * @description Encounter unique identifier
             */
            id?: string;
            /**
             * Format: uuid
             * @description Attending doctor's profile identifier
             */
            doctorId?: string;
            /**
             * @description Doctor full name and title
             * @example Dr. Gregory House
             */
            doctorName?: string;
            /**
             * @description Doctor medical specialty
             * @example Diagnostics
             */
            doctorSpecialty?: string;
            /**
             * Format: date
             * @description Encounter consultation date
             * @example 2024-03-10
             */
            encounterDate?: string;
            /**
             * @description Primary diagnosis
             * @example Acute Bronchitis
             */
            diagnosis?: string;
            /** @description Clinical consultation notes entered by the doctor */
            clinicalNotes?: string;
            /**
             * Format: date-time
             * @description Timestamp when recorded in vault
             */
            createdAt?: string;
        };
        /** @description Structured numerical lab test result for charting trends and clinical monitoring */
        LabTestResultResponse: {
            /**
             * Format: uuid
             * @description Unique lab test result UUID
             * @example d1eebc99-9c0b-4ef8-bb6d-6bb9bd380a55
             */
            id?: string;
            /**
             * Format: uuid
             * @description Patient profile UUID
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            patientId?: string;
            /**
             * Format: uuid
             * @description Ordering clinician or technician UUID
             * @example e2eebc99-9c0b-4ef8-bb6d-6bb9bd380a66
             */
            doctorId?: string;
            /**
             * @description Name of the clinician or technician who recorded the test
             * @example Dr. Gregory House
             */
            doctorName?: string;
            /**
             * @description Name of the diagnostic test or biomarker
             * @example Fasting Blood Glucose
             */
            testName?: string;
            /**
             * @description Numerical result of the test
             * @example 95.5
             */
            numericValue?: number;
            /**
             * @description Standard unit of measurement
             * @example mg/dL
             */
            unit?: string;
            /**
             * Format: date-time
             * @description Timestamp when the specimen was recorded
             */
            recordedAt?: string;
            /**
             * Format: date-time
             * @description Audit timestamp of record creation
             */
            createdAt?: string;
        };
        /** @description Demographic summary of the patient profile */
        PatientProfileSummaryDto: {
            /**
             * Format: uuid
             * @description Patient profile unique identifier
             */
            id?: string;
            /**
             * @description First name
             * @example Jane
             */
            firstName?: string;
            /**
             * @description Last name
             * @example Doe
             */
            lastName?: string;
            /**
             * Format: date
             * @description Date of birth
             * @example 1990-05-15
             */
            dateOfBirth?: string;
            /**
             * @description Blood type
             * @example O+
             */
            bloodType?: string;
            /**
             * @description Gender identity
             * @example FEMALE
             */
            gender?: string;
            /**
             * Format: double
             * @description Height in centimeters
             * @example 172.5
             */
            heightCm?: number;
            /**
             * Format: double
             * @description Weight in kilograms
             * @example 65
             */
            weightKg?: number;
        };
        /** @description Prescription details for pharmacy dispensing and clinical audit */
        PrescriptionResponse: {
            /**
             * Format: uuid
             * @description Prescription unique identifier
             * @example c2eebc99-9c0b-4ef8-bb6d-6bb9bd380a33
             */
            id?: string;
            /**
             * Format: uuid
             * @description Patient profile UUID
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            patientId?: string;
            /**
             * Format: uuid
             * @description Prescribing doctor profile UUID
             * @example d3eebc99-9c0b-4ef8-bb6d-6bb9bd380a44
             */
            doctorId?: string;
            /**
             * @description Prescribing doctor's full name
             * @example Dr. Gregory House
             */
            doctorName?: string;
            /**
             * Format: uuid
             * @description Optional linked clinical encounter UUID
             * @example b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22
             */
            encounterId?: string;
            /**
             * @description Name and strength of prescribed medication
             * @example Amoxicillin 500mg
             */
            medicationName?: string;
            /**
             * @description Prescribed dosage instructions
             * @example 1
             */
            dosage?: string;
            /**
             * @description Dispensing instructions and patient directions
             * @example Take with food for 7 days. Complete full course.
             */
            instructions?: string;
            /**
             * @description Current prescription lifecycle status
             * @example ACTIVE
             * @enum {string}
             */
            status?: "ACTIVE" | "FULFILLED" | "CANCELLED";
            /**
             * Format: date-time
             * @description Timestamp when the prescription was issued
             */
            issuedAt?: string;
            /**
             * Format: date-time
             * @description Timestamp when the prescription expires
             */
            expiresAt?: string;
        };
        /** @description Unlocked patient vault details returned after successful PIN verification handshake */
        UnlockedVaultResponse: {
            /** @description Patient basic demographic profile */
            patient?: components["schemas"]["PatientProfileSummaryDto"];
            /** @description Patient declared and doctor-verified allergies */
            allergies?: components["schemas"]["HealthConditionResponse"][];
            /** @description Patient declared and doctor-verified chronic conditions */
            chronicConditions?: components["schemas"]["HealthConditionResponse"][];
            /** @description All recorded health conditions and past medical history */
            allConditions?: components["schemas"]["HealthConditionResponse"][];
            /** @description Chronological past consultation encounter history */
            encounterHistory?: components["schemas"]["ClinicalEncounterSummaryDto"][];
            /**
             * Format: uuid
             * @description Scoped 24-hour active vault session UUID
             * @example f4eebc99-9c0b-4ef8-bb6d-6bb9bd380a77
             */
            activeSessionId?: string;
            /**
             * Format: date-time
             * @description Timestamp when the 24-hour consultation session expires
             */
            sessionExpiresAt?: string;
            /** @description Active and past prescriptions (accessible to clinicians and pharmacists) */
            prescriptions?: components["schemas"]["PrescriptionResponse"][];
            /** @description Biometric and diagnostic lab test results */
            testResults?: components["schemas"]["LabTestResultResponse"][];
        };
        /** @description Payload for logging a numerical lab test result or biometric measurement */
        CreateLabTestResultRequest: {
            /**
             * Format: uuid
             * @description UUID of the patient recipient
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            patientId: string;
            /**
             * @description Name of the diagnostic test or biomarker
             * @example Fasting Blood Glucose
             */
            testName: string;
            /**
             * @description Numerical result of the test
             * @example 95.5
             */
            numericValue: number;
            /**
             * @description Standard unit of measurement
             * @example mg/dL
             */
            unit: string;
            /**
             * Format: date-time
             * @description Timestamp when the specimen was drawn or test was executed
             */
            recordedAt: string;
        };
        /** @description Payload for doctor prescription issuance */
        CreatePrescriptionRequest: {
            /**
             * Format: uuid
             * @description UUID of the patient recipient
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            patientId: string;
            /**
             * Format: uuid
             * @description Optional clinical encounter UUID if prescribed during a consultation
             * @example b1eebc99-9c0b-4ef8-bb6d-6bb9bd380a22
             */
            encounterId?: string;
            /**
             * @description Name and strength of the prescribed drug
             * @example Amoxicillin 500mg
             */
            medicationName: string;
            /**
             * @description Dosage schedule
             * @example 1
             */
            dosage: string;
            /**
             * @description Instructions for patient and dispensing pharmacy
             * @example Take with food for 7 days. Complete full course.
             */
            instructions: string;
            /**
             * Format: date-time
             * @description Prescription validity expiration timestamp
             */
            expiresAt: string;
        };
        /** @description Payload to log an append-only clinical consultation encounter */
        CreateEncounterRequest: {
            /**
             * Format: uuid
             * @description Patient profile unique identifier
             */
            patientId: string;
            /** @example Persistent dry cough and mild chest tightness for 5 days */
            chiefComplaint?: string;
            /** @example Acute Tracheobronchitis */
            diagnosis: string;
            /** @example Lungs clear bilaterally on auscultation. Recommended hydration, rest, and short-term bronchodilator therapy. */
            clinicalNotes: string;
            /**
             * Format: date
             * @example 2024-03-15
             */
            encounterDate: string;
            /** @description Optional list of conditions/allergies diagnosed during this encounter (automatically tagged as DOCTOR_VERIFIED) */
            conditionsToAdd?: components["schemas"]["DoctorConditionInput"][];
        };
        /** @description Condition to record during an encounter with verified doctor source */
        DoctorConditionInput: {
            /** @example Type 2 Diabetes Mellitus */
            title: string;
            /**
             * @example CHRONIC_CONDITION
             * @enum {string}
             */
            type: "ALLERGY" | "CHRONIC_CONDITION" | "LIFESTYLE" | "PAST_HISTORY" | "MEDICATION" | "SURGERY" | "OTHER";
        };
        /** @description Details of an appended clinical consultation encounter */
        ClinicalEncounterResponse: {
            /**
             * Format: uuid
             * @description Encounter unique identifier
             */
            id?: string;
            /**
             * Format: uuid
             * @description Patient profile unique identifier
             */
            patientId?: string;
            /**
             * Format: uuid
             * @description Attending doctor profile unique identifier
             */
            doctorId?: string;
            /**
             * @description Attending doctor's full name
             * @example Dr. Gregory House
             */
            doctorName?: string;
            /**
             * @description Attending doctor's clinical specialty
             * @example Diagnostics
             */
            doctorSpecialty?: string;
            /**
             * @description Patient chief complaint
             * @example Persistent dry cough
             */
            chiefComplaint?: string;
            /**
             * @description Primary clinical diagnosis
             * @example Acute Tracheobronchitis
             */
            diagnosis?: string;
            /** @description Comprehensive clinical consultation notes */
            clinicalNotes?: string;
            /**
             * Format: date
             * @description Date of consultation
             * @example 2024-03-15
             */
            encounterDate?: string;
            /**
             * Format: date-time
             * @description Immutable creation timestamp
             */
            createdAt?: string;
            /** @description Any companion health conditions recorded during this encounter with DOCTOR_VERIFIED status */
            conditionsAdded?: components["schemas"]["HealthConditionResponse"][];
        };
        /** @description Request body for patient account registration */
        RegisterPatientRequest: {
            /** @example patient@example.com */
            email: string;
            /** @example Secret123! */
            password: string;
            /** @example Jane */
            firstName: string;
            /** @example Doe */
            lastName: string;
            /**
             * Format: date
             * @example 1990-05-15
             */
            dateOfBirth: string;
            /** @example O+ */
            bloodType?: string;
        };
        /** @description Authentication response containing JWT token and user profile metadata */
        AuthResponse: {
            /**
             * @description Signed JWT Bearer token
             * @example eyJhbGciOiJIUzI1NiJ9...
             */
            token?: string;
            /**
             * @description Token type
             * @example Bearer
             */
            tokenType?: string;
            /**
             * Format: uuid
             * @description User unique identifier
             * @example a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11
             */
            userId?: string;
            /**
             * Format: uuid
             * @description Associated Patient or Doctor profile identifier
             * @example b1ffcd88-8b1c-4fe7-cc7e-7cc8ce491b22
             */
            profileId?: string;
            /**
             * @description Account role
             * @example ROLE_PATIENT
             * @enum {string}
             */
            role?: "ROLE_PATIENT" | "ROLE_DOCTOR" | "ROLE_ADMIN";
            /**
             * @description User email address
             * @example patient@example.com
             */
            email?: string;
            /**
             * @description User full display name
             * @example Jane Doe
             */
            fullName?: string;
        };
        /** @description Request body for doctor account registration */
        RegisterDoctorRequest: {
            /** @example doctor@hospital.org */
            email: string;
            /** @example DoctorSecret123! */
            password: string;
            /** @example Gregory */
            firstName: string;
            /** @example House */
            lastName: string;
            /** @example MD-98765432 */
            licenseNumber: string;
            /** @example Diagnostics & Nephrology */
            specialty: string;
            /**
             * @description Specific clinician or healthcare worker role (defaults to GENERAL_PRACTITIONER)
             * @example GENERAL_PRACTITIONER
             * @enum {string}
             */
            doctorRole?: "GENERAL_PRACTITIONER" | "SPECIALIST" | "LAB_TECHNICIAN" | "PHARMACIST";
        };
        /** @description Request body for user login */
        LoginRequest: {
            /** @example patient@example.com */
            email: string;
            /** @example Secret123! */
            password: string;
        };
        /** @description Payload for prescription status lifecycle transition */
        UpdatePrescriptionStatusRequest: {
            /**
             * @description Updated status for the prescription (FULFILLED by patient or CANCELLED by doctor)
             * @example FULFILLED
             * @enum {string}
             */
            status: "ACTIVE" | "FULFILLED" | "CANCELLED";
        };
        /** @description Request body to update patient profile baseline attributes */
        UpdatePatientProfileRequest: {
            firstName?: string;
            lastName?: string;
            dateOfBirth?: string;
            email?: string;
            /**
             * @description Gender identity (e.g. MALE, FEMALE, OTHER, PREFER_NOT_TO_SAY)
             * @example FEMALE
             */
            gender?: string;
            /**
             * Format: double
             * @description Height in centimeters
             * @example 172.5
             */
            heightCm?: number;
            /**
             * Format: double
             * @description Weight in kilograms
             * @example 65
             */
            weightKg?: number;
            /**
             * @description Blood type (e.g. A+, O-, B+)
             * @example O+
             */
            bloodType?: string;
        };
        /** @description Detailed patient profile response */
        PatientProfileResponse: {
            /**
             * Format: uuid
             * @description Patient profile unique identifier
             */
            id?: string;
            /**
             * Format: uuid
             * @description Associated user unique identifier
             */
            userId?: string;
            /**
             * @description Patient first name
             * @example Jane
             */
            firstName?: string;
            /**
             * @description Patient last name
             * @example Doe
             */
            lastName?: string;
            /**
             * Format: date
             * @description Date of birth
             * @example 1990-05-15
             */
            dateOfBirth?: string;
            /**
             * @description Blood type
             * @example O+
             */
            bloodType?: string;
            /**
             * @description Gender identity
             * @example FEMALE
             */
            gender?: string;
            /**
             * Format: double
             * @description Height in centimeters
             * @example 172.5
             */
            heightCm?: number;
            /**
             * Format: double
             * @description Weight in kilograms
             * @example 65
             */
            weightKg?: number;
            /**
             * Format: date-time
             * @description Profile creation timestamp
             */
            createdAt?: string;
        };
        /** @description Request body for updating a doctor's active permission role for presentation demos */
        UpdateDoctorRoleRequest: {
            /**
             * @description Target doctor permission role
             * @example LAB_TECHNICIAN
             * @enum {string}
             */
            doctorRole: "GENERAL_PRACTITIONER" | "SPECIALIST" | "LAB_TECHNICIAN" | "PHARMACIST";
        };
        /** @description Response confirming doctor permission role update */
        DoctorRoleUpdateResponse: {
            /**
             * Format: uuid
             * @description Doctor profile UUID
             * @example d3eebc99-9c0b-4ef8-bb6d-6bb9bd380a44
             */
            doctorId?: string;
            /**
             * @description Doctor's full name
             * @example Dr. Gregory House
             */
            doctorName?: string;
            /**
             * @description Updated doctor permission role
             * @example LAB_TECHNICIAN
             * @enum {string}
             */
            doctorRole?: "GENERAL_PRACTITIONER" | "SPECIALIST" | "LAB_TECHNICIAN" | "PHARMACIST";
            /**
             * @description Status confirmation message
             * @example Doctor permission role successfully updated.
             */
            message?: string;
        };
        /** @description Consolidated chronological view of the patient vault including baseline health data and clinical encounters */
        PatientVaultTimelineResponse: {
            /** @description Patient basic demographic profile */
            patient?: components["schemas"]["PatientProfileSummaryDto"];
            /** @description Baseline health conditions and allergies */
            conditions?: components["schemas"]["HealthConditionResponse"][];
            /** @description Chronological clinical consultations (sorted descending) */
            encounters?: components["schemas"]["ClinicalEncounterSummaryDto"][];
        };
        /** @description Details of the currently authenticated user */
        CurrentUserResponse: {
            /**
             * Format: uuid
             * @description User unique identifier
             */
            userId?: string;
            /**
             * Format: uuid
             * @description Patient or Doctor profile unique identifier
             */
            profileId?: string;
            /** @description User email address */
            email?: string;
            /**
             * @description User account role
             * @enum {string}
             */
            role?: "ROLE_PATIENT" | "ROLE_DOCTOR" | "ROLE_ADMIN";
            /** @description Full name of the user or doctor */
            fullName?: string;
            /**
             * Format: date
             * @description Date of birth (patient profiles)
             * @example 1990-05-15
             */
            dateOfBirth?: string;
            /**
             * @description Blood type (patient profiles)
             * @example O+
             */
            bloodType?: string;
            /**
             * @description Gender identity (patient profiles)
             * @example FEMALE
             */
            gender?: string;
            /**
             * Format: double
             * @description Height in centimeters (patient profiles)
             * @example 172.5
             */
            heightCm?: number;
            /**
             * Format: double
             * @description Weight in kilograms (patient profiles)
             * @example 65
             */
            weightKg?: number;
            /**
             * Format: date-time
             * @description Account creation timestamp
             */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    syncBaselineConditions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncBaselineConditionsRequest"];
            };
        };
        responses: {
            /** @description Baseline conditions synchronized successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthConditionResponse"][];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    syncBaselineConditions_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SyncBaselineConditionsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthConditionResponse"][];
                };
            };
        };
    };
    getConditions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of conditions retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthConditionResponse"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addCondition: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateHealthConditionRequest"];
            };
        };
        responses: {
            /** @description Condition recorded successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["HealthConditionResponse"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generateAccessGrant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Access grant generated successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AccessGrantResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    unlockVault: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnlockVaultRequest"];
            };
        };
        responses: {
            /** @description Patient vault unlocked successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UnlockedVaultResponse"];
                };
            };
            /** @description Invalid, expired, or already used access PIN */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_DOCTOR */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    recordTestResult: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLabTestResultRequest"];
            };
        };
        responses: {
            /** @description Lab test result recorded successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LabTestResultResponse"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires active 24h session and authorized doctor role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Patient or doctor not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    issuePrescription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePrescriptionRequest"];
            };
        };
        responses: {
            /** @description Prescription issued successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrescriptionResponse"];
                };
            };
            /** @description Invalid request payload or encounter patient mismatch */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_DOCTOR */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Patient, doctor, or encounter not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createEncounter: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEncounterRequest"];
            };
        };
        responses: {
            /** @description Clinical encounter successfully recorded */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ClinicalEncounterResponse"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_DOCTOR */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Patient or doctor profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerPatient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterPatientRequest"];
            };
        };
        responses: {
            /** @description Patient successfully registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid request payload or validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    registerDoctor: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterDoctorRequest"];
            };
        };
        responses: {
            /** @description Doctor successfully registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid request payload or validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Email or license number already registered */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authentication successful */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Invalid email or password */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                prescriptionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePrescriptionStatusRequest"];
            };
        };
        responses: {
            /** @description Prescription status updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrescriptionResponse"];
                };
            };
            /** @description Invalid status transition or validation failure */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Not authorized to update this prescription */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Prescription not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePatientProfileRequest"];
            };
        };
        responses: {
            /** @description Patient profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatientProfileResponse"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Patient profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Patient profile retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatientProfileResponse"];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Patient profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateProfile_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePatientProfileRequest"];
            };
        };
        responses: {
            /** @description Patient profile updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatientProfileResponse"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Patient profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateDoctorRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                doctorId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDoctorRoleRequest"];
            };
        };
        responses: {
            /** @description Doctor role updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["DoctorRoleUpdateResponse"];
                };
            };
            /** @description Invalid request payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ADMIN or DOCTOR role */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Doctor profile not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTimeline: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Vault timeline retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PatientVaultTimelineResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTestResults: {
        parameters: {
            query?: {
                testName?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lab test results retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["LabTestResultResponse"][];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getPrescriptions: {
        parameters: {
            query?: {
                status?: "ACTIVE" | "FULFILLED" | "CANCELLED";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of prescriptions retrieved successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["PrescriptionResponse"][];
                };
            };
            /** @description Unauthorized - Missing or invalid JWT */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Requires ROLE_PATIENT */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user retrieved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["CurrentUserResponse"];
                };
            };
            /** @description Unauthorized or missing/expired JWT token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteCondition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conditionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Condition successfully removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - Cannot delete doctor-verified conditions */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Condition not found or does not belong to patient */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
